1단계 - 자바 reflection
NewKrew2021/jwp-mvc-kakao pull request #1
Opened 2020-12-15 02:38 UTC by humbledude

안녕하세요~

잘부탁드립니다 ㅎㅎ

2020-12-15 13:03 UTC, dongjoon1251 requested changes
테스트 결과가 모두 잘 나오는 것을 확인했습니다.
몇가지 코멘트 드렸습니다. 확인 부탁드립니다 :)

2020-12-15 13:03 UTC, dongjoon1251 commented on src/test/java/next/reflection/ReflectionTest.java
> +
생성자와 메소드의 접근자, 파라미터를 모두 출력해보면 어떨까요?
정확히 어떤 수준까지 정보를 출력해야하는지 기준이 없어서 이부분은 필수로 변경하지 않으셔도 될 것 같습니다.

2020-12-15 13:03 UTC, dongjoon1251 commented on src/test/java/next/reflection/Junit3TestRunner.java
> +                        method.invoke(clazz.newInstance());
clazz.newInstance()는 변수로 분리해서 외부에서 한번만 호출하게 하면 어떨까요 :)

2020-12-15 13:03 UTC, dongjoon1251 commented on src/test/java/next/reflection/ReflectionTest.java
> +        Field name = clazz.getDeclaredField("name");
name을 할당하고 확인하는 부분, age를 할당하고 확인하는 부분에 코드 중복이 있는 것 같습니다. 
공통 로직을 메소드로 분리하고, assert  구문 2개로 메소드 내부를 줄여보면 어떨까요? :)

2020-12-15 13:03 UTC, dongjoon1251 commented on src/test/java/next/reflection/ReflectionTest.java
> +        Class<Question> clazz = Question.class;
모든 생성자에 대해서 테스트해보면 어떨까요? :)

2020-12-15 13:03 UTC, dongjoon1251 commented on src/test/java/core/di/factory/BeanFactoryTest.java
> +        logger.debug("controllers ------");
메소드로 분리해서 코드중복을 줄여보면 어떨까요? :)

2020-12-15 14:09 UTC, humbledude commented on src/test/java/next/reflection/ReflectionTest.java
> +
네 ㅎㅎㅎ 이럴때 해보는거죠 ㅎㅎㅎ 함 해보겠습니다 ㅎㅎ

2020-12-15 14:10 UTC, humbledude commented on src/test/java/next/reflection/ReflectionTest.java
> +        Field name = clazz.getDeclaredField("name");
네 ㅎㅎ 제가 테스트 코드라고 생각하고 넘 막짰네요 ㅎㅎㅎ
다시 해보겠습니다 ㅎㅎ

2020-12-15 15:26 UTC, humbledude commented
@dongjoon1251 
안녕하세요~ ㅎㅎ
주신 피드백 반영해 보았습니다 ㅎㅎ
테스트 코드에 작성한다고 너무 대충 했군요~!!
다음부턴 신경좀 쓰도록 하겠습니다 ㅎㅎ

2020-12-16 02:00 UTC, dongjoon1251 approved these changes
변경사항 확인했습니다 :) 다음 단계 진행하시죠 ㅎㅎ

2020-12-16 02:00 UTC, merged