Step2 - @MVC 구현
NewKrew2021/jwp-mvc-kakao pull request #3
Opened 2020-12-24 01:04 UTC by sehan

### 요구사항
* 애노테이션 기반 MVC 프레임워크
* 레거시 MVC와 애노테이션 기반 MVC 통합

### 애노테이션 기반 MVC 프레임워크
AnnotationHandlerMapping 을 구현했습니다. 
@Controller 가 붙은 Class 에서 @RequestMapping 된 method 를 자동으로 매핑합니다.  method.invoke 시 사용될 인스턴스는 InstanceFactory 를 사용해서 생성하도록 했습니다. instance 를 매번 새로생성하거나 BeanFactory 를 활용해서 bean 을 재사용하는 부분은 상세구현에 의존하도록 했습니다. 

### 레거시 MVC와 애노테이션 기반 MVC 통합
레거시 MVC 와 애노테이션 기반 MVC 의 공존을 위해 request 를 처리해주는 RequestHandler 를 만들었습니다.
LegacyRequestHandler 는 레거시 MVC 방식의 구현체 입니다.
AnnotationSupportRequestHandler 는 애노테이션 기반 MVC 방식의 구현체 입니다.
마이그레이션이 완료되기 전까지는 두 handler 가 공존하다가  완료되면 LegacyRequestHandler 를 제거하는 방식으로 통합전략을 가져가려고 합니다.

리뷰 부탁드려요 😄

2020-12-26 13:12 UTC, karian7 requested changes
간결하게 잘 구현해주신 것 같습니다. 👍
 몇가지 질문이 있어 Request Change 하였습니다.

참고) `[도전]` 이 붙은 부분은 필수 구현사항은 아닙니다. :)

2020-12-26 13:12 UTC, karian7 commented on src/test/java/next/reflection/ReflectionTest.java
> +                .usingRecursiveComparison().isEqualTo(new Question(1L, "nio", "title", "contents", now, 0));
👍

2020-12-26 13:12 UTC, karian7 commented on src/test/java/core/mvc/tobe/InstanceFactoryTest.java
> +        instanceFactory = InstanceFactory.allNew();
[질문] 다른 미션에서 니오코드를 잠깐 봤는데 테스트 객체에서 필드를 분리하여 base class 에 선언하는 스타일을 쓰시는것 같더군요. 테스트 클래스테에 선언된 필드를 안보이도록 함으로서 집중도를 올리시려는 목적이신가요?

2020-12-26 13:12 UTC, karian7 commented on src/main/java/core/mvc/tobe/InstanceFactory.java
> +class SimpleInstanceFactory implements InstanceFactory {
[질문] 이 구현은 사용안되는것 같은데요. 혹시 어떤 용도인지 궁금합니다.

2020-12-26 13:12 UTC, karian7 commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +    private class Pair<K, V> {
내부적으로 필요한 객체를 만드셨군요 👍
자바는 왜 이런걸 제공 안하는지 모르겠어요 😞
저는 이런경우 아쉬운대로 `AbstractMap.SimpleEntry` 쓰긴해요.

2020-12-26 13:12 UTC, karian7 commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +                            .forEach(method -> addHandlerExecution(controller, method));
중첩 `forEach` 문이 조금 복잡하게 느껴지는데요. 상위 스트림에 `flatMap` 을 사용해서 뎁스를 줄여보는건 어떨까요?

2020-12-26 13:12 UTC, karian7 commented on src/main/java/core/mvc/RequestHandler.java
> +    static RequestHandler legacy(RequestMapping mapping) {
[질문] `InstanceFactory#allNew` 에서도 봤는데 인터페이스 내에 팩토리 메소드를 두는 기법(?)을 즐겨 사용하시는 것 같습니다. 이 팩토리 메소드의 경우 인터페이스와 구현체가 양방향으로 의존하게 되어서 DIP 를 지키지 못하게 되는 단점이 보이는데요, 이런 기법의 장점을 설명해 주실 수 있을까요?

2020-12-26 13:12 UTC, karian7 commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +                    mnv.getView().render(mnv.getModel(), req, resp);
[도전] `ForwardView` 를 만들면서 구현이 조금 바뀌었는데요, 레거시 컨트롤러를 어노테이션 컨트롤러로 바꾸기 용이하도록 view name 기반으로 구현하면 어떨까요?

2020-12-28 00:56 UTC, sehan commented on src/test/java/core/mvc/tobe/InstanceFactoryTest.java
> +        instanceFactory = InstanceFactory.allNew();
인터페이스를 구현하는 상세 구현체들이 지켜야 하는 명세(구현제약)을 test 코드를 통해 보장해서 상세 구현체들이 설계의도를 벗어나지 않도록 하는 의도로 작성하고 있습니다. 

InstanceFactory 의 경우는 그런의도에 맞는 test 코드가 InstanceFactoryTest 에 전혀 없어서 현재코드는 의도에 전혀 부합하지 못하고 있네요 😔

인터페이스로 설계한 경우 의도적으로 test 를 위와 같은 스타일로 작성하고 속을 채우려고 보니 채워넣은 알맹이(인터페이스 명세) 가 손에 잡히지 않아서 상세구현체에 test 매소드를 하나 작성하게 된 상황입니다. ☺️

2020-12-28 01:02 UTC, sehan commented on src/main/java/core/mvc/tobe/InstanceFactory.java
> +class SimpleInstanceFactory implements InstanceFactory {
InstanceFactory 는 AnnotationHandlerMapping 에서 @RequestMapping 이 붙은 method 실행을 위해 controller instance 가 필요하게 되는데 이때 instance 를 만들어 주는 역할을 합니다.

SimpleInstanceFactory 를 instance 를 만들어 줄때 항상 생성해서 주는것보다 BeanFactory 도 가지고 있으니 BeanFactory 를 활용해서 이미 Bean 으로 등록되어 있는것들은 재사용하도록 하려고 만든 구현체 입니다.

구현 후 코드에 적용하려고 보니 DispatcherServlet 에 BeanFactory 를 사용하고 있는 곳이 없어서 as-is / to-be MVC 구현이 모두 존재하는 상황에서 BeanFactory 를 넣는것이 큰 의미가 없어서 보여서 구현만 해놓고 AnnotationHandlerMapping 생성시 사용하지 않았습니다. 

그래서, 사용되지 못한 채로 구현채만 덩그러니 남았네요 😳

2020-12-28 01:48 UTC, sehan commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +                            .forEach(method -> addHandlerExecution(controller, method));
flatMap 으로 처리하니 훨씬 간결해 졌네요 👍

2020-12-28 01:59 UTC, sehan commented on src/main/java/core/mvc/RequestHandler.java
> +    static RequestHandler legacy(RequestMapping mapping) {
네, 맞습니다. 이 구현체의 경우 인터페이스가 구현체의 생성인자를 그대로 받고 있어서 DIP 를 위배하고 있습니다.
RequestHandler 의 경우 코드가독성 측면만 보고 인터페이스 내에 정적 팩토리 매소드를 추가 했습니다. RequestHandler 가 100% 통합 이후에는 삭제될 코드이기도 해서 좀 나이브한 마음가짐으로 슬쩍 넣어 두었습니다. 😄

다른 코드에서는 주로 인터페이스의 production 구현체를 만들기 전에 기본구현체 ( for 테스트 코드 작성이나 인터페이스 설계 검증을 위해 ) 들은 인터페이스에 정적 팩토리 매소드를 추가해서 작성하는 기법(?) 을 사용했습니다.  기법까지는 아니고 단순히 제 취향인거 같습니다.  그래서 개인적으로는 설계를 빠르게 검증하고 테스트 하기 위해 이런 기법을 사용하고 있습니다. 

다른 미션에서도 구현의 성향이 미션이다 보니 인터페이스에 팩토리 매소드들이 자주 등장해서 제 설계를 빠르게( 제 기준으로 ) 검증하는 용도로 사용했습니다.

2020-12-28 02:08 UTC, sehan commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +                    mnv.getView().render(mnv.getModel(), req, resp);
😓 이 부분을 손댈까 하다가... 코드가 길어질거 같아서 ( 사실.... 개을러서 ) 그냥 덥어 두었습니다
일단 도전 접수해 두겠습니다. 언제 다시 꺼내들지는 미확정입니다 ㅎㅎ

2020-12-28 02:52 UTC, karian7 approved these changes
https://github.com/next-step/jwp-mvc-kakao/pull/3#discussion_r549190438 자세한 설명 감사합니다. 🙇 👍 
다른 댓글도 자세히 설명해 주셔서 이해할 수 있었습니다.
다음단계로 gogo~ 🚀

2020-12-28 02:52 UTC, karian7 commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +                .forEach( handlerKeyAndExecutionPair -> addHandlerExecution(handlerKeyAndExecutionPair.getKey(), handlerKeyAndExecutionPair.getValue()));
```java
        controllers.stream()
                .flatMap(it -> Arrays.stream(it.getDeclaredMethods())
                                .filter(method -> method.isAnnotationPresent(RequestMapping.class))
                                .map( method -> Pair.of( it, method ))
                )
                .forEach( handlerKeyAndExecutionPair -> addHandlerExecution(handlerKeyAndExecutionPair.getKey(), handlerKeyAndExecutionPair.getValue()));
```
이런식으로 하면 리스트를 한번 덜 만들수도 있을것 같습니다. 😀

2020-12-28 02:52 UTC, karian7 commented on src/test/java/core/mvc/tobe/InstanceFactoryTest.java
> +}
https://github.com/next-step/jwp-mvc-kakao/pull/3#discussion_r549183430 댓글을 이해했습니다.
그렇다면 `AllNewFactorTest#create` 테스트 메소드를 `InstanceFactoryTest#create` 로 옮겨야 겠네요 😀

2020-12-28 02:52 UTC, merged

2020-12-28 02:57 UTC, sehan commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +                .forEach( handlerKeyAndExecutionPair -> addHandlerExecution(handlerKeyAndExecutionPair.getKey(), handlerKeyAndExecutionPair.getValue()));
😊 그러네요. 👍